/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout-success'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ShareShareIdRouteImport } from './routes/share.$shareId'
import { Route as ResultResultIdRouteImport } from './routes/result.$resultId'
import { Route as ProcessingJobIdRouteImport } from './routes/processing.$jobId'
import { Route as PreviewUploadIdRouteImport } from './routes/preview.$uploadId'
import { Route as DownloadUploadIdRouteImport } from './routes/download.$uploadId'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout-success',
  path: '/checkout-success',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ShareShareIdRoute = ShareShareIdRouteImport.update({
  id: '/share/$shareId',
  path: '/share/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultResultIdRoute = ResultResultIdRouteImport.update({
  id: '/result/$resultId',
  path: '/result/$resultId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingJobIdRoute = ProcessingJobIdRouteImport.update({
  id: '/processing/$jobId',
  path: '/processing/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewUploadIdRoute = PreviewUploadIdRouteImport.update({
  id: '/preview/$uploadId',
  path: '/preview/$uploadId',
  getParentRoute: () => rootRouteImport,
} as any)
const DownloadUploadIdRoute = DownloadUploadIdRouteImport.update({
  id: '/download/$uploadId',
  path: '/download/$uploadId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/download/$uploadId': typeof DownloadUploadIdRoute
  '/preview/$uploadId': typeof PreviewUploadIdRoute
  '/processing/$jobId': typeof ProcessingJobIdRoute
  '/result/$resultId': typeof ResultResultIdRoute
  '/share/$shareId': typeof ShareShareIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/download/$uploadId': typeof DownloadUploadIdRoute
  '/preview/$uploadId': typeof PreviewUploadIdRoute
  '/processing/$jobId': typeof ProcessingJobIdRoute
  '/result/$resultId': typeof ResultResultIdRoute
  '/share/$shareId': typeof ShareShareIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/download/$uploadId': typeof DownloadUploadIdRoute
  '/preview/$uploadId': typeof PreviewUploadIdRoute
  '/processing/$jobId': typeof ProcessingJobIdRoute
  '/result/$resultId': typeof ResultResultIdRoute
  '/share/$shareId': typeof ShareShareIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout-success'
    | '/faq'
    | '/how-it-works'
    | '/pricing'
    | '/download/$uploadId'
    | '/preview/$uploadId'
    | '/processing/$jobId'
    | '/result/$resultId'
    | '/share/$shareId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout-success'
    | '/faq'
    | '/how-it-works'
    | '/pricing'
    | '/download/$uploadId'
    | '/preview/$uploadId'
    | '/processing/$jobId'
    | '/result/$resultId'
    | '/share/$shareId'
  id:
    | '__root__'
    | '/'
    | '/checkout-success'
    | '/faq'
    | '/how-it-works'
    | '/pricing'
    | '/download/$uploadId'
    | '/preview/$uploadId'
    | '/processing/$jobId'
    | '/result/$resultId'
    | '/share/$shareId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PricingRoute: typeof PricingRoute
  DownloadUploadIdRoute: typeof DownloadUploadIdRoute
  PreviewUploadIdRoute: typeof PreviewUploadIdRoute
  ProcessingJobIdRoute: typeof ProcessingJobIdRoute
  ResultResultIdRoute: typeof ResultResultIdRoute
  ShareShareIdRoute: typeof ShareShareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-success': {
      id: '/checkout-success'
      path: '/checkout-success'
      fullPath: '/checkout-success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/share/$shareId': {
      id: '/share/$shareId'
      path: '/share/$shareId'
      fullPath: '/share/$shareId'
      preLoaderRoute: typeof ShareShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$resultId': {
      id: '/result/$resultId'
      path: '/result/$resultId'
      fullPath: '/result/$resultId'
      preLoaderRoute: typeof ResultResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing/$jobId': {
      id: '/processing/$jobId'
      path: '/processing/$jobId'
      fullPath: '/processing/$jobId'
      preLoaderRoute: typeof ProcessingJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$uploadId': {
      id: '/preview/$uploadId'
      path: '/preview/$uploadId'
      fullPath: '/preview/$uploadId'
      preLoaderRoute: typeof PreviewUploadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/download/$uploadId': {
      id: '/download/$uploadId'
      path: '/download/$uploadId'
      fullPath: '/download/$uploadId'
      preLoaderRoute: typeof DownloadUploadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  PricingRoute: PricingRoute,
  DownloadUploadIdRoute: DownloadUploadIdRoute,
  PreviewUploadIdRoute: PreviewUploadIdRoute,
  ProcessingJobIdRoute: ProcessingJobIdRoute,
  ResultResultIdRoute: ResultResultIdRoute,
  ShareShareIdRoute: ShareShareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
