/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as HowItWorksRouteImport } from './routes/how-it-works'
import { Route as FaqRouteImport } from './routes/faq'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout-success'
import { Route as ForClinicsRouteRouteImport } from './routes/for-clinics/route'
import { Route as CompareRouteRouteImport } from './routes/compare/route'
import { Route as BlogRouteRouteImport } from './routes/blog/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForClinicsIndexRouteImport } from './routes/for-clinics/index'
import { Route as CompareIndexRouteImport } from './routes/compare/index'
import { Route as BlogIndexRouteImport } from './routes/blog/index'
import { Route as ShareShareIdRouteImport } from './routes/share.$shareId'
import { Route as ResultResultIdRouteImport } from './routes/result.$resultId'
import { Route as ProcessingJobIdRouteImport } from './routes/processing.$jobId'
import { Route as PreviewUploadIdRouteImport } from './routes/preview.$uploadId'
import { Route as ForClinicsSecurityRouteImport } from './routes/for-clinics/security'
import { Route as ForClinicsHowItWorksRouteImport } from './routes/for-clinics/how-it-works'
import { Route as ForClinicsCalculatorRouteImport } from './routes/for-clinics/calculator'
import { Route as DownloadUploadIdRouteImport } from './routes/download.$uploadId'
import { Route as CompareBabypeekVsSeebabyRouteImport } from './routes/compare/babypeek-vs-seebaby'
import { Route as CompareAiBabyGenerators2026RouteImport } from './routes/compare/ai-baby-generators-2026'
import { Route as BlogWhatWillMyBabyLookLikeRouteImport } from './routes/blog/what-will-my-baby-look-like'
import { Route as BlogSeebabyVsBabypeekRouteImport } from './routes/blog/seebaby-vs-babypeek'
import { Route as BlogPregnancyAnnouncementIdeasRouteImport } from './routes/blog/pregnancy-announcement-ideas'
import { Route as BlogHowAiBabyPortraitTechnologyWorksRouteImport } from './routes/blog/how-ai-baby-portrait-technology-works'
import { Route as BlogBestTimeFor4dUltrasoundRouteImport } from './routes/blog/best-time-for-4d-ultrasound'
import { Route as BlogAiChangingKeepsakeUltrasoundRouteImport } from './routes/blog/ai-changing-keepsake-ultrasound'
import { Route as BlogAiBabyFacePredictionCompleteGuideRouteImport } from './routes/blog/ai-baby-face-prediction-complete-guide'
import { Route as BlogAddOnServicesUltrasoundClinicRouteImport } from './routes/blog/add-on-services-ultrasound-clinic'
import { Route as Blog3dVs4dVsHdUltrasoundRouteImport } from './routes/blog/3d-vs-4d-vs-hd-ultrasound'

const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const HowItWorksRoute = HowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => rootRouteImport,
} as any)
const FaqRoute = FaqRouteImport.update({
  id: '/faq',
  path: '/faq',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout-success',
  path: '/checkout-success',
  getParentRoute: () => rootRouteImport,
} as any)
const ForClinicsRouteRoute = ForClinicsRouteRouteImport.update({
  id: '/for-clinics',
  path: '/for-clinics',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareRouteRoute = CompareRouteRouteImport.update({
  id: '/compare',
  path: '/compare',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRouteRoute = BlogRouteRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForClinicsIndexRoute = ForClinicsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ForClinicsRouteRoute,
} as any)
const CompareIndexRoute = CompareIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => CompareRouteRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRouteRoute,
} as any)
const ShareShareIdRoute = ShareShareIdRouteImport.update({
  id: '/share/$shareId',
  path: '/share/$shareId',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultResultIdRoute = ResultResultIdRouteImport.update({
  id: '/result/$resultId',
  path: '/result/$resultId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProcessingJobIdRoute = ProcessingJobIdRouteImport.update({
  id: '/processing/$jobId',
  path: '/processing/$jobId',
  getParentRoute: () => rootRouteImport,
} as any)
const PreviewUploadIdRoute = PreviewUploadIdRouteImport.update({
  id: '/preview/$uploadId',
  path: '/preview/$uploadId',
  getParentRoute: () => rootRouteImport,
} as any)
const ForClinicsSecurityRoute = ForClinicsSecurityRouteImport.update({
  id: '/security',
  path: '/security',
  getParentRoute: () => ForClinicsRouteRoute,
} as any)
const ForClinicsHowItWorksRoute = ForClinicsHowItWorksRouteImport.update({
  id: '/how-it-works',
  path: '/how-it-works',
  getParentRoute: () => ForClinicsRouteRoute,
} as any)
const ForClinicsCalculatorRoute = ForClinicsCalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => ForClinicsRouteRoute,
} as any)
const DownloadUploadIdRoute = DownloadUploadIdRouteImport.update({
  id: '/download/$uploadId',
  path: '/download/$uploadId',
  getParentRoute: () => rootRouteImport,
} as any)
const CompareBabypeekVsSeebabyRoute =
  CompareBabypeekVsSeebabyRouteImport.update({
    id: '/babypeek-vs-seebaby',
    path: '/babypeek-vs-seebaby',
    getParentRoute: () => CompareRouteRoute,
  } as any)
const CompareAiBabyGenerators2026Route =
  CompareAiBabyGenerators2026RouteImport.update({
    id: '/ai-baby-generators-2026',
    path: '/ai-baby-generators-2026',
    getParentRoute: () => CompareRouteRoute,
  } as any)
const BlogWhatWillMyBabyLookLikeRoute =
  BlogWhatWillMyBabyLookLikeRouteImport.update({
    id: '/what-will-my-baby-look-like',
    path: '/what-will-my-baby-look-like',
    getParentRoute: () => BlogRouteRoute,
  } as any)
const BlogSeebabyVsBabypeekRoute = BlogSeebabyVsBabypeekRouteImport.update({
  id: '/seebaby-vs-babypeek',
  path: '/seebaby-vs-babypeek',
  getParentRoute: () => BlogRouteRoute,
} as any)
const BlogPregnancyAnnouncementIdeasRoute =
  BlogPregnancyAnnouncementIdeasRouteImport.update({
    id: '/pregnancy-announcement-ideas',
    path: '/pregnancy-announcement-ideas',
    getParentRoute: () => BlogRouteRoute,
  } as any)
const BlogHowAiBabyPortraitTechnologyWorksRoute =
  BlogHowAiBabyPortraitTechnologyWorksRouteImport.update({
    id: '/how-ai-baby-portrait-technology-works',
    path: '/how-ai-baby-portrait-technology-works',
    getParentRoute: () => BlogRouteRoute,
  } as any)
const BlogBestTimeFor4dUltrasoundRoute =
  BlogBestTimeFor4dUltrasoundRouteImport.update({
    id: '/best-time-for-4d-ultrasound',
    path: '/best-time-for-4d-ultrasound',
    getParentRoute: () => BlogRouteRoute,
  } as any)
const BlogAiChangingKeepsakeUltrasoundRoute =
  BlogAiChangingKeepsakeUltrasoundRouteImport.update({
    id: '/ai-changing-keepsake-ultrasound',
    path: '/ai-changing-keepsake-ultrasound',
    getParentRoute: () => BlogRouteRoute,
  } as any)
const BlogAiBabyFacePredictionCompleteGuideRoute =
  BlogAiBabyFacePredictionCompleteGuideRouteImport.update({
    id: '/ai-baby-face-prediction-complete-guide',
    path: '/ai-baby-face-prediction-complete-guide',
    getParentRoute: () => BlogRouteRoute,
  } as any)
const BlogAddOnServicesUltrasoundClinicRoute =
  BlogAddOnServicesUltrasoundClinicRouteImport.update({
    id: '/add-on-services-ultrasound-clinic',
    path: '/add-on-services-ultrasound-clinic',
    getParentRoute: () => BlogRouteRoute,
  } as any)
const Blog3dVs4dVsHdUltrasoundRoute =
  Blog3dVs4dVsHdUltrasoundRouteImport.update({
    id: '/3d-vs-4d-vs-hd-ultrasound',
    path: '/3d-vs-4d-vs-hd-ultrasound',
    getParentRoute: () => BlogRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/compare': typeof CompareRouteRouteWithChildren
  '/for-clinics': typeof ForClinicsRouteRouteWithChildren
  '/checkout-success': typeof CheckoutSuccessRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/blog/3d-vs-4d-vs-hd-ultrasound': typeof Blog3dVs4dVsHdUltrasoundRoute
  '/blog/add-on-services-ultrasound-clinic': typeof BlogAddOnServicesUltrasoundClinicRoute
  '/blog/ai-baby-face-prediction-complete-guide': typeof BlogAiBabyFacePredictionCompleteGuideRoute
  '/blog/ai-changing-keepsake-ultrasound': typeof BlogAiChangingKeepsakeUltrasoundRoute
  '/blog/best-time-for-4d-ultrasound': typeof BlogBestTimeFor4dUltrasoundRoute
  '/blog/how-ai-baby-portrait-technology-works': typeof BlogHowAiBabyPortraitTechnologyWorksRoute
  '/blog/pregnancy-announcement-ideas': typeof BlogPregnancyAnnouncementIdeasRoute
  '/blog/seebaby-vs-babypeek': typeof BlogSeebabyVsBabypeekRoute
  '/blog/what-will-my-baby-look-like': typeof BlogWhatWillMyBabyLookLikeRoute
  '/compare/ai-baby-generators-2026': typeof CompareAiBabyGenerators2026Route
  '/compare/babypeek-vs-seebaby': typeof CompareBabypeekVsSeebabyRoute
  '/download/$uploadId': typeof DownloadUploadIdRoute
  '/for-clinics/calculator': typeof ForClinicsCalculatorRoute
  '/for-clinics/how-it-works': typeof ForClinicsHowItWorksRoute
  '/for-clinics/security': typeof ForClinicsSecurityRoute
  '/preview/$uploadId': typeof PreviewUploadIdRoute
  '/processing/$jobId': typeof ProcessingJobIdRoute
  '/result/$resultId': typeof ResultResultIdRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/blog/': typeof BlogIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/for-clinics/': typeof ForClinicsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout-success': typeof CheckoutSuccessRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/blog/3d-vs-4d-vs-hd-ultrasound': typeof Blog3dVs4dVsHdUltrasoundRoute
  '/blog/add-on-services-ultrasound-clinic': typeof BlogAddOnServicesUltrasoundClinicRoute
  '/blog/ai-baby-face-prediction-complete-guide': typeof BlogAiBabyFacePredictionCompleteGuideRoute
  '/blog/ai-changing-keepsake-ultrasound': typeof BlogAiChangingKeepsakeUltrasoundRoute
  '/blog/best-time-for-4d-ultrasound': typeof BlogBestTimeFor4dUltrasoundRoute
  '/blog/how-ai-baby-portrait-technology-works': typeof BlogHowAiBabyPortraitTechnologyWorksRoute
  '/blog/pregnancy-announcement-ideas': typeof BlogPregnancyAnnouncementIdeasRoute
  '/blog/seebaby-vs-babypeek': typeof BlogSeebabyVsBabypeekRoute
  '/blog/what-will-my-baby-look-like': typeof BlogWhatWillMyBabyLookLikeRoute
  '/compare/ai-baby-generators-2026': typeof CompareAiBabyGenerators2026Route
  '/compare/babypeek-vs-seebaby': typeof CompareBabypeekVsSeebabyRoute
  '/download/$uploadId': typeof DownloadUploadIdRoute
  '/for-clinics/calculator': typeof ForClinicsCalculatorRoute
  '/for-clinics/how-it-works': typeof ForClinicsHowItWorksRoute
  '/for-clinics/security': typeof ForClinicsSecurityRoute
  '/preview/$uploadId': typeof PreviewUploadIdRoute
  '/processing/$jobId': typeof ProcessingJobIdRoute
  '/result/$resultId': typeof ResultResultIdRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/blog': typeof BlogIndexRoute
  '/compare': typeof CompareIndexRoute
  '/for-clinics': typeof ForClinicsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteRouteWithChildren
  '/compare': typeof CompareRouteRouteWithChildren
  '/for-clinics': typeof ForClinicsRouteRouteWithChildren
  '/checkout-success': typeof CheckoutSuccessRoute
  '/faq': typeof FaqRoute
  '/how-it-works': typeof HowItWorksRoute
  '/pricing': typeof PricingRoute
  '/blog/3d-vs-4d-vs-hd-ultrasound': typeof Blog3dVs4dVsHdUltrasoundRoute
  '/blog/add-on-services-ultrasound-clinic': typeof BlogAddOnServicesUltrasoundClinicRoute
  '/blog/ai-baby-face-prediction-complete-guide': typeof BlogAiBabyFacePredictionCompleteGuideRoute
  '/blog/ai-changing-keepsake-ultrasound': typeof BlogAiChangingKeepsakeUltrasoundRoute
  '/blog/best-time-for-4d-ultrasound': typeof BlogBestTimeFor4dUltrasoundRoute
  '/blog/how-ai-baby-portrait-technology-works': typeof BlogHowAiBabyPortraitTechnologyWorksRoute
  '/blog/pregnancy-announcement-ideas': typeof BlogPregnancyAnnouncementIdeasRoute
  '/blog/seebaby-vs-babypeek': typeof BlogSeebabyVsBabypeekRoute
  '/blog/what-will-my-baby-look-like': typeof BlogWhatWillMyBabyLookLikeRoute
  '/compare/ai-baby-generators-2026': typeof CompareAiBabyGenerators2026Route
  '/compare/babypeek-vs-seebaby': typeof CompareBabypeekVsSeebabyRoute
  '/download/$uploadId': typeof DownloadUploadIdRoute
  '/for-clinics/calculator': typeof ForClinicsCalculatorRoute
  '/for-clinics/how-it-works': typeof ForClinicsHowItWorksRoute
  '/for-clinics/security': typeof ForClinicsSecurityRoute
  '/preview/$uploadId': typeof PreviewUploadIdRoute
  '/processing/$jobId': typeof ProcessingJobIdRoute
  '/result/$resultId': typeof ResultResultIdRoute
  '/share/$shareId': typeof ShareShareIdRoute
  '/blog/': typeof BlogIndexRoute
  '/compare/': typeof CompareIndexRoute
  '/for-clinics/': typeof ForClinicsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/compare'
    | '/for-clinics'
    | '/checkout-success'
    | '/faq'
    | '/how-it-works'
    | '/pricing'
    | '/blog/3d-vs-4d-vs-hd-ultrasound'
    | '/blog/add-on-services-ultrasound-clinic'
    | '/blog/ai-baby-face-prediction-complete-guide'
    | '/blog/ai-changing-keepsake-ultrasound'
    | '/blog/best-time-for-4d-ultrasound'
    | '/blog/how-ai-baby-portrait-technology-works'
    | '/blog/pregnancy-announcement-ideas'
    | '/blog/seebaby-vs-babypeek'
    | '/blog/what-will-my-baby-look-like'
    | '/compare/ai-baby-generators-2026'
    | '/compare/babypeek-vs-seebaby'
    | '/download/$uploadId'
    | '/for-clinics/calculator'
    | '/for-clinics/how-it-works'
    | '/for-clinics/security'
    | '/preview/$uploadId'
    | '/processing/$jobId'
    | '/result/$resultId'
    | '/share/$shareId'
    | '/blog/'
    | '/compare/'
    | '/for-clinics/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout-success'
    | '/faq'
    | '/how-it-works'
    | '/pricing'
    | '/blog/3d-vs-4d-vs-hd-ultrasound'
    | '/blog/add-on-services-ultrasound-clinic'
    | '/blog/ai-baby-face-prediction-complete-guide'
    | '/blog/ai-changing-keepsake-ultrasound'
    | '/blog/best-time-for-4d-ultrasound'
    | '/blog/how-ai-baby-portrait-technology-works'
    | '/blog/pregnancy-announcement-ideas'
    | '/blog/seebaby-vs-babypeek'
    | '/blog/what-will-my-baby-look-like'
    | '/compare/ai-baby-generators-2026'
    | '/compare/babypeek-vs-seebaby'
    | '/download/$uploadId'
    | '/for-clinics/calculator'
    | '/for-clinics/how-it-works'
    | '/for-clinics/security'
    | '/preview/$uploadId'
    | '/processing/$jobId'
    | '/result/$resultId'
    | '/share/$shareId'
    | '/blog'
    | '/compare'
    | '/for-clinics'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/compare'
    | '/for-clinics'
    | '/checkout-success'
    | '/faq'
    | '/how-it-works'
    | '/pricing'
    | '/blog/3d-vs-4d-vs-hd-ultrasound'
    | '/blog/add-on-services-ultrasound-clinic'
    | '/blog/ai-baby-face-prediction-complete-guide'
    | '/blog/ai-changing-keepsake-ultrasound'
    | '/blog/best-time-for-4d-ultrasound'
    | '/blog/how-ai-baby-portrait-technology-works'
    | '/blog/pregnancy-announcement-ideas'
    | '/blog/seebaby-vs-babypeek'
    | '/blog/what-will-my-baby-look-like'
    | '/compare/ai-baby-generators-2026'
    | '/compare/babypeek-vs-seebaby'
    | '/download/$uploadId'
    | '/for-clinics/calculator'
    | '/for-clinics/how-it-works'
    | '/for-clinics/security'
    | '/preview/$uploadId'
    | '/processing/$jobId'
    | '/result/$resultId'
    | '/share/$shareId'
    | '/blog/'
    | '/compare/'
    | '/for-clinics/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRouteRoute: typeof BlogRouteRouteWithChildren
  CompareRouteRoute: typeof CompareRouteRouteWithChildren
  ForClinicsRouteRoute: typeof ForClinicsRouteRouteWithChildren
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  FaqRoute: typeof FaqRoute
  HowItWorksRoute: typeof HowItWorksRoute
  PricingRoute: typeof PricingRoute
  DownloadUploadIdRoute: typeof DownloadUploadIdRoute
  PreviewUploadIdRoute: typeof PreviewUploadIdRoute
  ProcessingJobIdRoute: typeof ProcessingJobIdRoute
  ResultResultIdRoute: typeof ResultResultIdRoute
  ShareShareIdRoute: typeof ShareShareIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/how-it-works': {
      id: '/how-it-works'
      path: '/how-it-works'
      fullPath: '/how-it-works'
      preLoaderRoute: typeof HowItWorksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/faq': {
      id: '/faq'
      path: '/faq'
      fullPath: '/faq'
      preLoaderRoute: typeof FaqRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout-success': {
      id: '/checkout-success'
      path: '/checkout-success'
      fullPath: '/checkout-success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-clinics': {
      id: '/for-clinics'
      path: '/for-clinics'
      fullPath: '/for-clinics'
      preLoaderRoute: typeof ForClinicsRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare': {
      id: '/compare'
      path: '/compare'
      fullPath: '/compare'
      preLoaderRoute: typeof CompareRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-clinics/': {
      id: '/for-clinics/'
      path: '/'
      fullPath: '/for-clinics/'
      preLoaderRoute: typeof ForClinicsIndexRouteImport
      parentRoute: typeof ForClinicsRouteRoute
    }
    '/compare/': {
      id: '/compare/'
      path: '/'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof CompareRouteRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/compare/': {
      id: '/compare/'
      path: '/'
      fullPath: '/compare/'
      preLoaderRoute: typeof CompareIndexRouteImport
      parentRoute: typeof CompareRouteRoute
    }
    '/share/$shareId': {
      id: '/share/$shareId'
      path: '/share/$shareId'
      fullPath: '/share/$shareId'
      preLoaderRoute: typeof ShareShareIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/result/$resultId': {
      id: '/result/$resultId'
      path: '/result/$resultId'
      fullPath: '/result/$resultId'
      preLoaderRoute: typeof ResultResultIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/processing/$jobId': {
      id: '/processing/$jobId'
      path: '/processing/$jobId'
      fullPath: '/processing/$jobId'
      preLoaderRoute: typeof ProcessingJobIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/preview/$uploadId': {
      id: '/preview/$uploadId'
      path: '/preview/$uploadId'
      fullPath: '/preview/$uploadId'
      preLoaderRoute: typeof PreviewUploadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/for-clinics/security': {
      id: '/for-clinics/security'
      path: '/security'
      fullPath: '/for-clinics/security'
      preLoaderRoute: typeof ForClinicsSecurityRouteImport
      parentRoute: typeof ForClinicsRouteRoute
    }
    '/for-clinics/how-it-works': {
      id: '/for-clinics/how-it-works'
      path: '/how-it-works'
      fullPath: '/for-clinics/how-it-works'
      preLoaderRoute: typeof ForClinicsHowItWorksRouteImport
      parentRoute: typeof ForClinicsRouteRoute
    }
    '/for-clinics/calculator': {
      id: '/for-clinics/calculator'
      path: '/calculator'
      fullPath: '/for-clinics/calculator'
      preLoaderRoute: typeof ForClinicsCalculatorRouteImport
      parentRoute: typeof ForClinicsRouteRoute
    }
    '/download/$uploadId': {
      id: '/download/$uploadId'
      path: '/download/$uploadId'
      fullPath: '/download/$uploadId'
      preLoaderRoute: typeof DownloadUploadIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/compare/babypeek-vs-seebaby': {
      id: '/compare/babypeek-vs-seebaby'
      path: '/babypeek-vs-seebaby'
      fullPath: '/compare/babypeek-vs-seebaby'
      preLoaderRoute: typeof CompareBabypeekVsSeebabyRouteImport
      parentRoute: typeof CompareRouteRoute
    }
    '/compare/ai-baby-generators-2026': {
      id: '/compare/ai-baby-generators-2026'
      path: '/ai-baby-generators-2026'
      fullPath: '/compare/ai-baby-generators-2026'
      preLoaderRoute: typeof CompareAiBabyGenerators2026RouteImport
      parentRoute: typeof CompareRouteRoute
    }
    '/blog/what-will-my-baby-look-like': {
      id: '/blog/what-will-my-baby-look-like'
      path: '/what-will-my-baby-look-like'
      fullPath: '/blog/what-will-my-baby-look-like'
      preLoaderRoute: typeof BlogWhatWillMyBabyLookLikeRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/seebaby-vs-babypeek': {
      id: '/blog/seebaby-vs-babypeek'
      path: '/seebaby-vs-babypeek'
      fullPath: '/blog/seebaby-vs-babypeek'
      preLoaderRoute: typeof BlogSeebabyVsBabypeekRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/pregnancy-announcement-ideas': {
      id: '/blog/pregnancy-announcement-ideas'
      path: '/pregnancy-announcement-ideas'
      fullPath: '/blog/pregnancy-announcement-ideas'
      preLoaderRoute: typeof BlogPregnancyAnnouncementIdeasRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/how-ai-baby-portrait-technology-works': {
      id: '/blog/how-ai-baby-portrait-technology-works'
      path: '/how-ai-baby-portrait-technology-works'
      fullPath: '/blog/how-ai-baby-portrait-technology-works'
      preLoaderRoute: typeof BlogHowAiBabyPortraitTechnologyWorksRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/best-time-for-4d-ultrasound': {
      id: '/blog/best-time-for-4d-ultrasound'
      path: '/best-time-for-4d-ultrasound'
      fullPath: '/blog/best-time-for-4d-ultrasound'
      preLoaderRoute: typeof BlogBestTimeFor4dUltrasoundRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/ai-changing-keepsake-ultrasound': {
      id: '/blog/ai-changing-keepsake-ultrasound'
      path: '/ai-changing-keepsake-ultrasound'
      fullPath: '/blog/ai-changing-keepsake-ultrasound'
      preLoaderRoute: typeof BlogAiChangingKeepsakeUltrasoundRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/ai-baby-face-prediction-complete-guide': {
      id: '/blog/ai-baby-face-prediction-complete-guide'
      path: '/ai-baby-face-prediction-complete-guide'
      fullPath: '/blog/ai-baby-face-prediction-complete-guide'
      preLoaderRoute: typeof BlogAiBabyFacePredictionCompleteGuideRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/add-on-services-ultrasound-clinic': {
      id: '/blog/add-on-services-ultrasound-clinic'
      path: '/add-on-services-ultrasound-clinic'
      fullPath: '/blog/add-on-services-ultrasound-clinic'
      preLoaderRoute: typeof BlogAddOnServicesUltrasoundClinicRouteImport
      parentRoute: typeof BlogRouteRoute
    }
    '/blog/3d-vs-4d-vs-hd-ultrasound': {
      id: '/blog/3d-vs-4d-vs-hd-ultrasound'
      path: '/3d-vs-4d-vs-hd-ultrasound'
      fullPath: '/blog/3d-vs-4d-vs-hd-ultrasound'
      preLoaderRoute: typeof Blog3dVs4dVsHdUltrasoundRouteImport
      parentRoute: typeof BlogRouteRoute
    }
  }
}

interface BlogRouteRouteChildren {
  Blog3dVs4dVsHdUltrasoundRoute: typeof Blog3dVs4dVsHdUltrasoundRoute
  BlogAddOnServicesUltrasoundClinicRoute: typeof BlogAddOnServicesUltrasoundClinicRoute
  BlogAiBabyFacePredictionCompleteGuideRoute: typeof BlogAiBabyFacePredictionCompleteGuideRoute
  BlogAiChangingKeepsakeUltrasoundRoute: typeof BlogAiChangingKeepsakeUltrasoundRoute
  BlogBestTimeFor4dUltrasoundRoute: typeof BlogBestTimeFor4dUltrasoundRoute
  BlogHowAiBabyPortraitTechnologyWorksRoute: typeof BlogHowAiBabyPortraitTechnologyWorksRoute
  BlogPregnancyAnnouncementIdeasRoute: typeof BlogPregnancyAnnouncementIdeasRoute
  BlogSeebabyVsBabypeekRoute: typeof BlogSeebabyVsBabypeekRoute
  BlogWhatWillMyBabyLookLikeRoute: typeof BlogWhatWillMyBabyLookLikeRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteRouteChildren: BlogRouteRouteChildren = {
  Blog3dVs4dVsHdUltrasoundRoute: Blog3dVs4dVsHdUltrasoundRoute,
  BlogAddOnServicesUltrasoundClinicRoute:
    BlogAddOnServicesUltrasoundClinicRoute,
  BlogAiBabyFacePredictionCompleteGuideRoute:
    BlogAiBabyFacePredictionCompleteGuideRoute,
  BlogAiChangingKeepsakeUltrasoundRoute: BlogAiChangingKeepsakeUltrasoundRoute,
  BlogBestTimeFor4dUltrasoundRoute: BlogBestTimeFor4dUltrasoundRoute,
  BlogHowAiBabyPortraitTechnologyWorksRoute:
    BlogHowAiBabyPortraitTechnologyWorksRoute,
  BlogPregnancyAnnouncementIdeasRoute: BlogPregnancyAnnouncementIdeasRoute,
  BlogSeebabyVsBabypeekRoute: BlogSeebabyVsBabypeekRoute,
  BlogWhatWillMyBabyLookLikeRoute: BlogWhatWillMyBabyLookLikeRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteRouteWithChildren = BlogRouteRoute._addFileChildren(
  BlogRouteRouteChildren,
)

interface CompareRouteRouteChildren {
  CompareAiBabyGenerators2026Route: typeof CompareAiBabyGenerators2026Route
  CompareBabypeekVsSeebabyRoute: typeof CompareBabypeekVsSeebabyRoute
  CompareIndexRoute: typeof CompareIndexRoute
}

const CompareRouteRouteChildren: CompareRouteRouteChildren = {
  CompareAiBabyGenerators2026Route: CompareAiBabyGenerators2026Route,
  CompareBabypeekVsSeebabyRoute: CompareBabypeekVsSeebabyRoute,
  CompareIndexRoute: CompareIndexRoute,
}

const CompareRouteRouteWithChildren = CompareRouteRoute._addFileChildren(
  CompareRouteRouteChildren,
)

interface ForClinicsRouteRouteChildren {
  ForClinicsCalculatorRoute: typeof ForClinicsCalculatorRoute
  ForClinicsHowItWorksRoute: typeof ForClinicsHowItWorksRoute
  ForClinicsSecurityRoute: typeof ForClinicsSecurityRoute
  ForClinicsIndexRoute: typeof ForClinicsIndexRoute
}

const ForClinicsRouteRouteChildren: ForClinicsRouteRouteChildren = {
  ForClinicsCalculatorRoute: ForClinicsCalculatorRoute,
  ForClinicsHowItWorksRoute: ForClinicsHowItWorksRoute,
  ForClinicsSecurityRoute: ForClinicsSecurityRoute,
  ForClinicsIndexRoute: ForClinicsIndexRoute,
}

const ForClinicsRouteRouteWithChildren = ForClinicsRouteRoute._addFileChildren(
  ForClinicsRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRouteRoute: BlogRouteRouteWithChildren,
  CompareRouteRoute: CompareRouteRouteWithChildren,
  ForClinicsRouteRoute: ForClinicsRouteRouteWithChildren,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  FaqRoute: FaqRoute,
  HowItWorksRoute: HowItWorksRoute,
  PricingRoute: PricingRoute,
  DownloadUploadIdRoute: DownloadUploadIdRoute,
  PreviewUploadIdRoute: PreviewUploadIdRoute,
  ProcessingJobIdRoute: ProcessingJobIdRoute,
  ResultResultIdRoute: ResultResultIdRoute,
  ShareShareIdRoute: ShareShareIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
